### ISSUE TITLE
mint-ui button 样式问题

### ISSUE THREAD

**Issue by flybbjcs70** [ElemeFE/mint-ui#125]
```css
.mint-button {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border-radius: 4px;
    border: 0;
    box-sizing: border-box;
    color: inherit;
    display: block;
    font-size: 18px;
    height: 41px;
    line-height: 41.6px;
    line-height: 2.6rem;
    outline: 0;
    overflow: hidden;
    position: relative;
    text-align: center
}
```

俩line-height 是啥意思，
我的rem值比较大，文字都跑外面去了...
