### ISSUE TITLE
field组件如何在左侧显示小icon呢？

### ISSUE THREAD

**Issue by WebCodeFarmer** [ElemeFE/mint-ui#529]
目前只支持在右侧显示icon，但是很多时候，左侧也需要一些icon

**Comment by galenyuan** [comment]
```css
.mint-field .mint-cell-value {
    flex-direction: row-reverse;
}
```
可以这样覆写CSS，也可以用slot的方式自订制，以后会考虑加配置项
