### ISSUE TITLE
建议组件不要写行内样式，会导致无法定制样式

### ISSUE THREAD

**Issue by zhengguorong** [ElemeFE/mint-ui#636]
例如加载中控件：indicator.vue
该行样式这样写的`<div class="mint-indicator-wrapper" :style="{ 'padding': text ? '20px' : '15px' }">`

当我用了rem做适配时，loading显示会很小，而且我无法通过样式覆盖。

**Comment by galenyuan** [comment]
```css
.mint-indicator-wrapper {
  padding: 1rem !important;
}
```
